apiVersion: core.choreo.dev/v1
kind: DataPlane
metadata:
  annotations:
    core.choreo.dev/description: DataPlane "default-dataplane" was created through
      the script.
    core.choreo.dev/display-name: DataPlane "default-dataplane"
  labels:
    core.choreo.dev/name: default-dataplane
    core.choreo.dev/organization: default-org
  name: default-dataplane
  namespace: default-org
spec:
  registry:
    push:
      unauthenticated:
        - docker.io/test
        - registry.choreo-system:5000
      imagePushSecrets:
        - name: dev-dockerhub-push-secret
          prefix: docker.io/your-org
        - name: dev-ghcr-push-secret
          prefix: ghcr.io/your-org
    pull:
      unauthenticated:
        - docker.io/test
        - registry.choreo-system:5000
      imagePushSecrets:
        - name: dev-dockerhub-push-secret
          prefix: docker.io/your-org
        - name: dev-ghcr-push-secret
          prefix: ghcr.io/your-org
  gateway:
    organizationVirtualHost: choreoapis.internal
    publicVirtualHost: choreoapis.localhost
  kubernetesCluster:
    credentials:
      apiServerURL: https://choreo-dp-control-plane:6443
      caCert: s
      clientCert: s
      clientKey: s==
    name: kind-choreo-dp
