apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-docker-image-
  namespace: argo-build
spec:
  serviceAccountName: argo-workflow
  entrypoint: build-workflow
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: workspace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - kind-worker2

  templates:
    - name: build-workflow
      steps:
        - - name: clone-repo
            template: clone-repository
        - - name: build-image
            template: build-step

    - name: clone-repository
      container:
        image: alpine/git
        command: ["sh", "-c"]
        args:
          - |
            set -e
            echo "Cloning repository from the main branch..."
            git clone --single-branch --branch dev https://github.com/chalindukodikara/choreo-samples.git /mnt/vol/choreo-samples
            echo "Repository cloned successfully."
            echo "Can go into docker-time-logger-schedule"
        volumeMounts:
          - name: workspace
            mountPath: /mnt/vol
# Heroku
# pack build test-01-heroku:v1.1 --builder=heroku/builder:24 --pull-policy if-not-present

# Paketo
#
