apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: go-workflow-template-cluster-workflow-01
  namespace: choreo-ci-default-org
spec:
  workflowTemplateRef:
    name: go-workflow-template-cluster
    clusterScope: true