
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: choreo-ci-default-org
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World"  