apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-template-usage-004
  namespace: choreo-ci-default-org
spec:
  entrypoint: build-workflow
  serviceAccountName: workflow-sa
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: workspace
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  volumes:
  - hostPath:
      path: /shared/podman/cache
      type: DirectoryOrCreate
    name: podman-cache
  templates:
    - name: build-workflow
      steps:
        - - name: clone-step
            templateRef:
              name: default-workflow-template
              template: clone-step
        - - name: build-step
            templateRef:
              name: default-workflow-template
              template: build-step
            arguments:
              parameters:
                - name: git-revision
                  value: "{{steps.clone-step.outputs.parameters.git-revision}}"
