apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: default-workflow-template
  namespace: choreo-ci-default-org
spec:
  serviceAccountName: workflow-sa
  templates:
    - name: clone-step
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            set -e
            git clone --single-branch --branch main --depth 1 https://github.com/wso2/choreo-samples /mnt/vol/source
            cd /mnt/vol/source
            COMMIT_SHA=$(git rev-parse HEAD)
            echo -n "$COMMIT_SHA" | cut -c1-8 > /tmp/git-revision.txt
        volumeMounts:
        - mountPath: /mnt/vol
          name: workspace
      outputs:
        parameters:
          - name: git-revision
            valueFrom:
              path: /tmp/git-revision.txt
      metadata:
        labels:
          step: clone-step
          workflow: reading-list-service-build-01

    - name: build-step
      inputs:
        parameters:
          - name: git-revision
      container:
        image: ghcr.io/openchoreo/podman-runner:v1.0
        command: [sh, -c]
        args:
        - |-
          set -e

          mkdir -p /etc/containers
          cat <<EOF > /etc/containers/storage.conf
          [storage]
          driver = "overlay"
          runroot = "/run/containers/storage"
          graphroot = "/var/lib/containers/storage"
          [storage.options.overlay]
          mount_program = "/usr/bin/fuse-overlayfs"
          EOF
          podman system service --time=0 &
          until podman info --format '{{.Host.RemoteSocket.Exists}}' 2>/dev/null | grep -q "true"; do
            sleep 1
          done

          if [[ ! -f "/shared/podman/cache/google-builder.tar" ]]; then
            podman pull gcr.io/buildpacks/builder:google-22
            podman save -o /shared/podman/cache/google-builder.tar gcr.io/buildpacks/builder:google-22
          else
            if ! podman load -i /shared/podman/cache/google-builder.tar; then
              podman pull gcr.io/buildpacks/builder:google-22
              podman save -o /shared/podman/cache/google-builder.tar gcr.io/buildpacks/builder:google-22
            fi
          fi


          if [[ ! -f "/shared/podman/cache/google-run.tar" ]]; then
            podman pull gcr.io/buildpacks/google-22/run:latest
            podman save -o /shared/podman/cache/google-run.tar gcr.io/buildpacks/google-22/run:latest
          else
            if ! podman load -i /shared/podman/cache/google-run.tar; then
              podman pull gcr.io/buildpacks/google-22/run:latest
              podman save -o /shared/podman/cache/google-run.tar gcr.io/buildpacks/google-22/run:latest
            fi
          fi

          /usr/local/bin/pack build default-org-default-project-reading-list-service-08512f5d:reading-list-service-main-33d882c8-{{inputs.parameters.git-revision}} --builder=gcr.io/buildpacks/builder:google-22 \
          --docker-host=inherit --path=/mnt/vol/source/go-reading-list-rest-api --pull-policy if-not-present --env GOOGLE_GO_VERSION="1.x"

          podman save -o /mnt/vol/app-image.tar default-org-default-project-reading-list-service-08512f5d:reading-list-service-main-33d882c8-{{inputs.parameters.git-revision}}
        volumeMounts:
        - mountPath: /mnt/vol
          name: workspace
        - mountPath: /shared/podman/cache
          name: podman-cache
        securityContext:
          privileged: true
      metadata:
        labels:
          step: build-step
          workflow: reading-list-service-build-01
