apiVersion: core.choreo.dev/v1
kind: Build
metadata:
  name: go-build
  namespace: default-org
spec:
  classRef: default-buildpack-class

  # Optional
  repository:
    url: https://github.com/wso2/choreo-samples
    revision:
      # branch: main
      commit: 4061be9
    appPath: /go-reading-list-rest-api

  # Optional
  parameters:
    context: /go-reading-list-rest-api
    dockerfilePath: /go-reading-list-rest-api/Dockerfile
    language: go
    version: 1.21
    # Docker build args (`--build-arg`)
    buildArgs:
      NODE_VERSION: 18
      APP_VERSION: v1.0.0

    # Pack CLI environment variables (`--env`)
    env:
      BP_GO_VERSION: 1.21
      APP_ENV: production

    # Common options used for both Docker and Buildpacks
    docker-host: inherit
    platform: linux/arm64
