apiVersion: core.choreo.dev/v1
kind: ComponentV2
metadata:
  name: reading-list-service
#  namespace: default-org
spec:
  type: Service
  owner:
    projectName: default-project

  # Defines how to create the artifact
  build: 
    # Optional
    repository:
      url: https://github.com/wso2/choreo-samples
      revision:
        branch: main
        # commit: 4061be9 # No need for component?
      appPath: /go-reading-list-rest-api

    # Optional
    parameters:
      context: /go-reading-list-rest-api
      dockerfilePath: /go-reading-list-rest-api/Dockerfile
      language: go
      version: 1.21
      # Docker build args (`--build-arg`)
      buildArgs:
        NODE_VERSION: 18
        APP_VERSION: v1.0.0

      # Pack CLI environment variables (`--env`)
      env:
        BP_GO_VERSION: 1.21
        APP_ENV: production

      # Common options used for both Docker and Buildpacks
      docker-host: inherit
      platform: linux/arm64

  # Defines how the component is configured during deployment
  workload:
    className: go-service-standard
    # Defines how to deploy the component
    type: Service
    image: ghcr.io/openchoreo/samples/greeter-service:latest
    command: [ "./go-greeter" ]
    args: [ "--port", "9090" ]
    env:
      - key: LOG_LEVEL
        value: "info"
      - key: GITHUB_REPOSITORY
        valueFrom:
          configurationGroupRef:
            name: github
            key: repository
      - key: GITHUB_TOKEN
        valueFrom:
          configurationGroupRef:
            name: github
            key: pat
    envFrom: [ ]
    fileMounts: [ ]
    fileMountsFrom: [ ]