apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind
  namespace: dp-test-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          args: ["--host=tcp://0.0.0.0:2375"]