apiVersion: v1
data:
  .dockerconfigjson: ==
kind: Secret
metadata:
  name: docker-pull-secret-hello-world
  namespace: choreo-system
  annotations:
    replicator.v1.mittwald.de/replicate-to: "dp-.*"
type: kubernetes.io/dockerconfigjson
